---

- name: gather facts
  hosts: localhost
  connection: local
  roles:
    - k8s-source

- name: apply desired state
  hosts: localhost
  connection: local
  roles:
    - k8s-state
  environment: "{{ k8s_state_source_env }}"
