---

- name: "{{ k8s_application.name }} : verify application parameters"
  assert:
    that:
      - k8s_application.name is string
      - "'{{ playbook_dir }}/cache/k8s-state-source/apps/{{ k8s_application.name }}' is exists"

- name: "{{ k8s_application.name }} : create namespace"
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: klifter-system-app-{{ k8s_application.name }}
        labels:
          app.kubernetes.io/managed-by: klifter
          app.kubernetes.io/component: application
          app.kubernetes.io/name: {{ k8s_application.name }}
      EOF
  changed_when: false

- name: "{{ k8s_application.name }} : deploy application"
  shell: kapp deploy -n 'klifter-system-app-{{ k8s_application.name }}' -a '{{ k8s_application.name }}' -f '{{ playbook_dir }}/cache/k8s-state-source/apps/{{ k8s_application.name }}'
  changed_when: false
