---

- name: install tools
  include_tasks: tools/{{ k8s_tool }}.yml
  loop: "{{ k8s_state_default_tools + k8s_state_source_vars.tools }}"
  loop_control:
    loop_var: k8s_tool

- name: deploy packages
  include_tasks: "{{ k8s_package.kind }}.yml"
  loop: "{{ k8s_state_source_vars.packages }}"
  loop_control:
    loop_var: k8s_package
