---

- name: "docker : add repository key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: "docker : add repository"
  become: yes
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: "docker : update cache"
  become: yes
  shell: apt update
  changed_when: false

- name: "docker : install packages"
  become: yes
  shell: apt install -y --no-install-recommends docker-ce docker-ce-cli containerd.io
  changed_when: false
